services:
  - type: web
    name: image-classification-backend
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false # Allow manual setting on Dashboard
      - key: CORS_ALLOWED_ORIGINS
        sync: false # Allow manual setting on Dashboard
      - key: CSRF_TRUSTED_ORIGINS
        sync: false # Allow manual setting on Dashboard
      - key: DATABASE_URL
        sync: false # This will be automatically set by the Postgres add-on
    autoDeploy: true 